# Generated by Django 5.1.2 on 2025-04-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooks', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenbook',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='liked_cooks', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='kitchenbook',
            name='followed_cooks',
            field=models.ManyToManyField(related_name='followers', to='cooks.cook'),
        ),
        migrations.AddField(
            model_name='kitchenbook',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_book', to='cooks.cook'),
        ),
    ]
