# Generated by Django 5.1.2 on 2025-03-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='phone',
        ),
        migrations.AlterField(
            model_name='cook',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='media/profile_pictures/'),
        ),
    ]
