# Generated by Django 5.1.2 on 2025-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cook',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cook',
            name='threads',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cook',
            name='x',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
