# Generated by Django 5.1.2 on 2025-03-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_remove_cook_phone_alter_cook_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
