# Generated by Django 5.1.2 on 2025-03-31 16:29

import cooks.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0005_alter_cook_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[django.core.validators.validate_image_file_extension, cooks.validators.validate_file_size]),
        ),
    ]
