# Generated by Django 5.1.2 on 2025-04-01 05:39

import cooks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0006_alter_cook_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[cooks.validators.validate_image_type, cooks.validators.validate_file_size]),
        ),
    ]
