# Generated by Django 5.1.2 on 2024-10-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='media/recipe_images/')),
                ('veganity_status', models.IntegerField(choices=[(1, 'Vegetarian'), (2, 'Non-Vegetarian'), (3, 'Egg Only')])),
                ('remove_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Removed')], default=1)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='products', to='recipes.category')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cooks.cook')),
            ],
        ),
    ]
