# Generated by Django 5.1.2 on 2025-04-02 09:39

import cooks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images/', validators=[cooks.validators.validate_file_size, cooks.validators.validate_image_type]),
        ),
    ]
