# Generated by Django 5.1.2 on 2025-05-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
