# Generated by Django 5.1.2 on 2024-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media/logos')),
                ('fevicon', models.ImageField(upload_to='media/logos')),
                ('tagline', models.TextField(max_length=200)),
            ],
        ),
    ]
