# Generated by Django 5.1.2 on 2025-03-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='banner',
            field=models.ImageField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='fevicon',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
